#!/system/xbin/bash

# kernel modules (compiled in kernel)
#insmod /system/lib/modules/snd-hwdep.ko
#insmod /system/lib/modules/snd-rawmidi.ko
#insmod /system/lib/modules/snd-usbmidi-lib.ko
#insmod /system/lib/modules/snd-usb-audio.ko

# Disable external record source by default.
if [ -c /dev/snd/pcmC2D0c ]; then
# valid values for usb.audio.cap.device: pcmCxDxc PCM audio device in /dev/snd folder
setprop usb.audio.cap.device pcmC0D0c
/system/bin/log -t usb-audio "### Disable external USB record source."
else
/system/bin/log -t usb-audio "### /dev/snd/pcmC2D0c does not exist. Nothing to be done."
fi
echo "USB audio init: DONE"
